services:
  db:
    image: mysql:latest
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      
    ports:
      - "4001:3306"